In [ ]:
from google.colab import drive
drive.mount('/content/drive')

print("Google Drive가 '/content/drive' 경로에 마운트되었습니다.")

Mounted at /content/drive
Google Drive가 '/content/drive' 경로에 마운트되었습니다.

In [ ]:
import os

# Google Drive 내의 특정 폴더 경로 설정
drive_path = '/content/drive/MyDrive/교통문제공모전/생활이동_행정동_202607'

# 해당 경로에 있는 파일 목록 확인
if os.path.exists(drive_path):
    print(f"'{drive_path}' 폴더 내용:")
    for item in os.listdir(drive_path):
        print(item)
else:
    print(f"⚠️ 경고: '{drive_path}' 경로를 찾을 수 없습니다. Google Drive 경로를 확인해주세요.")

'/content/drive/MyDrive/교통문제공모전/생활이동_행정동_202607' 폴더 내용:
생활이동_행정동_2026.07_14시.csv
생활이동_행정동_2026.07_13시.csv
생활이동_행정동_2026.07_12시.csv
생활이동_행정동_2026.07_11시.csv
생활이동_행정동_2026.07_10시.csv
생활이동_행정동_2026.07_09시.csv
생활이동_행정동_2026.07_08시.csv
생활이동_행정동_2026.07_05시.csv
생활이동_행정동_2026.07_07시.csv
생활이동_행정동_2026.07_06시.csv
생활이동_행정동_2026.07_00시.csv
생활이동_행정동_2026.07_01시.csv
생활이동_행정동_2026.07_03시.csv
생활이동_행정동_2026.07_04시.csv
생활이동_행정동_2026.07_02시.csv
생활이동_행정동_2026.07_15시.csv
생활이동_행정동_2026.07_16시.csv
생활이동_행정동_2026.07_17시.csv
생활이동_행정동_2026.07_18시.csv
생활이동_행정동_2026.07_19시.csv
생활이동_행정동_2026.07_20시.csv
생활이동_행정동_2026.07_21시.csv
생활이동_행정동_2026.07_22시.csv
생활이동_행정동_2026.07_23시.csv
combined_filtered_results.csv

**데이터셋에서 이동유형이 HW,WH(출/퇴근) 만 필터링** - 꽤 오래 걸림

In [ ]:
import pandas as pd
import glob
import os

# 1. 작업할 CSV 파일들이 있는 경로 설정
file_list = glob.glob(os.path.join(drive_path, '*.csv'))

# 2. 필터링된 결과 파일을 저장할 새 폴더 생성 (원본 보호 목적)
output_dir = 'filtered_results'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# 3. 파일 목록을 하나씩 꺼내서 반복 작업 실행
if not file_list:
    print("⚠️ 경고: 지정된 경로에서 CSV 파일을 찾을 수 없습니다.")
else:
    for file in file_list:
        try:
            # 데이터 불러오기
            df = pd.read_csv(file, encoding='cp949')

            # 특정 열(예: '이동유형')에서 원하는 값(예: 'WH', 'HW')만 필터링
            if '이동유형' in df.columns:  # 파일에 해당 열이 존재하는지 먼저 확인
                filtered_df = df[(df['이동유형'] == 'WH') | (df['이동유형'] == 'HW')]

                # 새로운 파일 경로 생성 (예: filtered_results/원본이름.csv)
                base_name = os.path.basename(file)
                output_path = os.path.join(output_dir, base_name)

                # 결과 저장
                filtered_df.to_csv(output_path, index=False, encoding='utf-8-sig')
                print(f"✅ 처리 완료: {base_name} (남은 행 수: {len(filtered_df)})")
            else:
                print(f"⚠️ 경고: '{base_name}' 파일에 '이동유형' 열이 없어 건너뜁니다.")

        except Exception as e:
            print(f"❌ 오류 발생 ({file}): {e}")

    print("모든 작업이 완료되었습니다!")

✅ 처리 완료: 생활이동_행정동_2026.07_14시.csv (남은 행 수: 1050225)
✅ 처리 완료: 생활이동_행정동_2026.07_13시.csv (남은 행 수: 1142200)
✅ 처리 완료: 생활이동_행정동_2026.07_12시.csv (남은 행 수: 1145571)
✅ 처리 완료: 생활이동_행정동_2026.07_11시.csv (남은 행 수: 1194044)
✅ 처리 완료: 생활이동_행정동_2026.07_10시.csv (남은 행 수: 1712365)
✅ 처리 완료: 생활이동_행정동_2026.07_09시.csv (남은 행 수: 2735628)
✅ 처리 완료: 생활이동_행정동_2026.07_08시.csv (남은 행 수: 3330216)
✅ 처리 완료: 생활이동_행정동_2026.07_05시.csv (남은 행 수: 390490)
✅ 처리 완료: 생활이동_행정동_2026.07_07시.csv (남은 행 수: 2094660)
✅ 처리 완료: 생활이동_행정동_2026.07_06시.csv (남은 행 수: 1073125)
✅ 처리 완료: 생활이동_행정동_2026.07_00시.csv (남은 행 수: 704490)
✅ 처리 완료: 생활이동_행정동_2026.07_01시.csv (남은 행 수: 370391)
✅ 처리 완료: 생활이동_행정동_2026.07_03시.csv (남은 행 수: 192160)
✅ 처리 완료: 생활이동_행정동_2026.07_04시.csv (남은 행 수: 204773)
✅ 처리 완료: 생활이동_행정동_2026.07_02시.csv (남은 행 수: 246060)
✅ 처리 완료: 생활이동_행정동_2026.07_15시.csv (남은 행 수: 1092202)
✅ 처리 완료: 생활이동_행정동_2026.07_16시.csv (남은 행 수: 1341283)
✅ 처리 완료: 생활이동_행정동_2026.07_17시.csv (남은 행 수: 1854948)
✅ 처리 완료: 생활이동_행정동_2026.07_18시.csv (남은 행 수: 2631937)
✅ 처리 완료: 생활이동_행정동_2026.07_19시.csv (남은 행 수: 2770891)
✅ 처리 완료: 생활이동_행정동_2026.07_20시.csv (남은 행 수: 2155838)
✅ 처리 완료: 생활이동_행정동_2026.07_21시.csv (남은 행 수: 1754730)
✅ 처리 완료: 생활이동_행정동_2026.07_22시.csv (남은 행 수: 1502742)
✅ 처리 완료: 생활이동_행정동_2026.07_23시.csv (남은 행 수: 1045117)
❌ 오류 발생 (/content/drive/MyDrive/교통문제공모전/생활이동_행정동_202607/combined_filtered_results.csv): 'cp949' codec can't decode byte 0x8c in position 4: illegal multibyte sequence
모든 작업이 완료되었습니다!

**필터링된 결과 파일들을 하나로 합치기**

In [ ]:
import pandas as pd
import glob
import os

# 필터링된 파일들이 저장된 디렉토리 설정
filtered_files_dir = 'filtered_results'

# 해당 디렉토리 내의 모든 CSV 파일 목록 가져오기
combined_file_list = glob.glob(os.path.join(filtered_files_dir, '*.csv'))

# 모든 데이터를 담을 빈 리스트 생성
all_filtered_dfs = []

# 각 파일을 읽어서 리스트에 추가
for file_path in combined_file_list:
    try:
        df = pd.read_csv(file_path)
        all_filtered_dfs.append(df)
        print(f"➕ 파일 추가: {os.path.basename(file_path)}")
    except Exception as e:
        print(f"❌ 파일 읽기 오류 ({os.path.basename(file_path)}): {e}")

# 리스트에 있는 모든 데이터프레임을 하나로 합치기
if all_filtered_dfs:
    combined_df = pd.concat(all_filtered_dfs, ignore_index=True)

    # 합쳐진 데이터 저장
    output_combined_path = 'combined_filtered_results.csv'
    combined_df.to_csv(output_combined_path, index=False, encoding='utf-8-sig')
    print(f"\n✅ 모든 필터링된 파일이 '{output_combined_path}'로 성공적으로 합쳐졌습니다. (총 {len(combined_df)} 행)")
    display(combined_df.head())
else:
    print("⚠️ 합칠 파일이 'filtered_results' 디렉토리에 없습니다.")

➕ 파일 추가: 생활이동_행정동_2026.07_09시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_04시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_12시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_11시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_13시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_19시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_14시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_02시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_03시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_01시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_15시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_16시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_00시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_06시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_21시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_23시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_07시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_17시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_08시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_05시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_22시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_10시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_18시.csv
➕ 파일 추가: 생활이동_행정동_2026.07_20시.csv

✅ 모든 필터링된 파일이 'combined_filtered_results.csv'로 성공적으로 합쳐졌습니다. (총 33736086 행)

     대상연월 요일  도착시간  출발 행정동 코드  도착 행정동 코드 성별  나이 이동유형  평균 이동 시간(분) 이동인구(합)
0  202607  일     9    1101053    1101053  F  15   HW            7    4.03
1  202607  일     9    1101053    1101053  F  35   HW           21    6.01
2  202607  일     9    1101053    1101053  F  40   HW           70    6.82
3  202607  일     9    1101053    1101053  F  50   HW            4    9.13
4  202607  일     9    1101053    1101053  F  50   WH            5    3.08

In [ ]:
display(combined_df.head(20))

      대상연월 요일  도착시간  출발 행정동 코드  도착 행정동 코드 성별  나이 이동유형  평균 이동 시간(분) 이동인구(합)
0   202607  일     9    1101053    1101053  F  15   HW            7    4.03
1   202607  일     9    1101053    1101053  F  35   HW           21    6.01
2   202607  일     9    1101053    1101053  F  40   HW           70    6.82
3   202607  일     9    1101053    1101053  F  50   HW            4    9.13
4   202607  일     9    1101053    1101053  F  50   WH            5    3.08
5   202607  일     9    1101053    1101053  F  55   HW           23    6.46
6   202607  일     9    1101053    1101053  F  65   HW           18   13.93
7   202607  일     9    1101053    1101053  F  70   HW            2    5.67
8   202607  일     9    1101053    1101053  F  75   WH           27    8.77
9   202607  일     9    1101053    1101053  M  10   HW           20    6.58
10  202607  일     9    1101053    1101053  M  25   HW           11    4.50
11  202607  일     9    1101053    1101053  M  30   WH           13       *
12  202607  일     9    1101053    1101053  M  35   HW          183       *
13  202607  일     9    1101053    1101053  M  40   HW           21       *
14  202607  일     9    1101053    1101053  M  40   WH           18    5.96
15  202607  일     9    1101053    1102055  M  55   HW           29    3.26
16  202607  일     9    1101053    1102057  F  40   WH            4    3.34
17  202607  일     9    1101053    1102060  F  60   HW           12    3.79
18  202607  일     9    1101053    1102070  F  40   HW           36    3.41
19  202607  일     9    1101053    1103051  M  45   WH           26    3.20

**합쳐진 csv 파일을 구글 드라이브에 저장**

In [ ]:
import shutil
import os

# 원본 파일 경로
source_file = 'combined_filtered_results.csv'

# Google Drive 내 저장할 경로 (이전에 사용된 drive_path 변수 활용)
destination_dir = drive_path # 또는 원하는 다른 Google Drive 경로 지정 가능
destination_file = os.path.join(destination_dir, os.path.basename(source_file))

# 대상 디렉토리가 없으면 생성
if not os.path.exists(destination_dir):
    os.makedirs(destination_dir)

try:
    shutil.copy(source_file, destination_file)
    print(f"✅ '{source_file}' 파일이 Google Drive '{destination_file}' 경로로 성공적으로 복사되었습니다.")
except FileNotFoundError:
    print(f"❌ 오류: '{source_file}' 파일을 찾을 수 없습니다. 파일이 현재 디렉토리에 있는지 확인하세요.")
except Exception as e:
    print(f"❌ 파일 복사 중 오류 발생: {e}")

✅ 'combined_filtered_results.csv' 파일이 Google Drive '/content/drive/MyDrive/교통문제공모전/생활이동_행정동_202607/combined_filtered_results.csv' 경로로 성공적으로 복사되었습니다.

- 인원이 매우 적은 이동(마스킹 처리된 이동)에 대해서는, 보통 이동 시간이 매우 크거나 매우 작은 특별한 경우로, 평균 시간 계산에 큰 영향을 줄 수 있으므로 계산에서 제외. 즉, 마스킹 처리된 값에 대해서는 결측치 취급하며, 그 행에 대해선 연산하지 않기로 함.

**각 행정동별 평균 출근시간/퇴근시간 계산하기**

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/교통문제공모전/생활이동_행정동_202607/combined_filtered_results.csv'
# '출발 행정동 코드'와 '도착 행정동 코드'를 문자열(str)로 명시하여 로드
combined_df = pd.read_csv(file_path, dtype={'출발 행정동 코드': str, '도착 행정동 코드': str})

In [ ]:
import pandas as pd
import numpy as np

# 1. '이동인구(합)' 컬럼 전처리
combined_df['이동인구_숫자'] = pd.to_numeric(combined_df['이동인구(합)'], errors='coerce')

# NaN 값을 어떻게 처리할지 결정 (여기서는 안전하게 계산에서 제외하도록 dropna 사용)
df_clean = combined_df.dropna(subset=['이동인구_숫자']).copy()

# 2. 총 이동 시간 계산 (평균 이동 시간 * 이동인구 수)
df_clean['총_이동시간'] = df_clean['평균 이동 시간(분)'] * df_clean['이동인구_숫자']

# --- 출근(HW) 데이터 분석 ---
# 3-1. 출근(HW) 데이터만 필터링
hw_df = df_clean[df_clean['이동유형'] == 'HW'].copy() # SettingWithCopyWarning 방지 위해 copy() 사용
# 4-1. 출발 행정동(거주지) 기준으로 그룹화하여 합계 구하기
grouped_hw = hw_df.groupby('출발 행정동 코드').agg(
    총_이동시간_합=('총_이동시간', 'sum'),
    총_이동인구_합=('이동인구_숫자', 'sum')).reset_index() # 그룹화된 컬럼을 일반 컬럼으로 변환

# 5. 최종 평균 출근 시간 구하기
grouped_hw['평균_출근_시간(분)'] = grouped_hw['총_이동시간_합'] / grouped_hw['총_이동인구_합']
print("--- 출근(HW) 데이터 분석 결과 (출발 행정동 코드별 평균 출근 시간) ---")
display(grouped_hw[['출발 행정동 코드', '평균_출근_시간(분)']].head(10))

# --- 퇴근(WH) 데이터 분석 ---
# 3-2. 퇴근(WH) 데이터만 필터링
wh_df = df_clean[df_clean['이동유형'] == 'WH'].copy() # SettingWithCopyWarning 방지 위해 copy() 사용
# 4-2. 도착 행정동(거주지) 기준으로 그룹화하여 합계 구하기 (퇴근 시 거주지는 도착 행정동)
grouped_wh = wh_df.groupby('도착 행정동 코드').agg(
    총_이동시간_합=('총_이동시간', 'sum'),
    총_이동인구_합=('이동인구_숫자', 'sum')).reset_index() # 그룹화된 컬럼을 일반 컬럼으로 변환

# 5. 최종 평균 퇴근 시간 구하기
grouped_wh['평균_퇴근_시간(분)'] = grouped_wh['총_이동시간_합'] / grouped_wh['총_이동인구_합']
print("\n--- 퇴근(WH) 데이터 분석 결과 (도착 행정동 코드별 평균 퇴근 시간) ---")
display(grouped_wh[['도착 행정동 코드', '평균_퇴근_시간(분)']].head(10))

--- 출근(HW) 데이터 분석 결과 (출발 행정동 코드별 평균 출근 시간) ---

  출발 행정동 코드  평균_출근_시간(분)
0   1101053    41.856244
1   1101054    41.163625
2   1101055    48.528842
3   1101056    54.670017
4   1101057    45.938627
5   1101058    45.508210
6   1101060    39.685682
7   1101061    43.896020
8   1101063    42.358243
9   1101064    44.811856

--- 퇴근(WH) 데이터 분석 결과 (도착 행정동 코드별 평균 퇴근 시간) ---

  도착 행정동 코드  평균_퇴근_시간(분)
0   1101053    43.714615
1   1101054    44.502381
2   1101055    47.098866
3   1101056    52.057282
4   1101057    47.381529
5   1101058    46.177299
6   1101060    42.631519
7   1101061    42.750959
8   1101063    44.169396
9   1101064    43.923824

In [ ]:
# 1. 출근(HW) 데이터 정리 및 저장
grouped_hw_save = grouped_hw[['출발 행정동 코드', '평균_출근_시간(분)']].copy()

# 구글 드라이브에 CSV 파일로 저장
hw_save_path = '/content/drive/MyDrive/교통문제공모전/avg_hw_time.csv'
grouped_hw.to_csv(hw_save_path, index=False, encoding='utf-8-sig')
print(f"✅ 출근 기준 데이터 저장 완료: {hw_save_path}")


# 2. 퇴근(WH) 데이터 정리 및 저장
grouped_wh_save = grouped_wh[['도착 행정동 코드', '평균_퇴근_시간(분)']].copy()

# 구글 드라이브에 CSV 파일로 저장
wh_save_path = '/content/drive/MyDrive/교통문제공모전/avg_wh_time.csv'
grouped_wh_save.to_csv(wh_save_path, index=False, encoding='utf-8-sig')
print(f"✅ 퇴근 기준 데이터 저장 완료: {wh_save_path}")

✅ 출근 기준 데이터 저장 완료: /content/drive/MyDrive/교통문제공모전/avg_hw_time.csv
✅ 퇴근 기준 데이터 저장 완료: /content/drive/MyDrive/교통문제공모전/avg_wh_time.csv